version: '2'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db_postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
      - ./metabase.db:/metabase.db
#    environment:
#      MB_DB_TYPE: postgres
#      MB_DB_DBNAME: metabase
#      MB_DB_PORT: 5432
#      MB_DB_USER: postgres
#      MB_DB_PASS: root
#      MB_DB_HOST: datamart-db
    depends_on:
      - db_postgres
    links:
      - db_postgres    

  webspoon:
    build: ./webspoon
    ports:
      - "8080:8080"
    volumes:
      - ./webspoon/shared:/home/tomcat/shared
      - kettle:/home/tomcat/.kettle
      - pentaho:/home/tomcat/.pentaho
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
    links:
      - db_postgres

volumes:
  kettle:
  pentaho: 
