-- MySQL Script generated by MySQL Workbench
-- qui 05 dez 2019 22:00:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE "DM_Northwind"

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS "public" CASCADE;

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  "public"  ;

-- -----------------------------------------------------
-- Table "public"."DIM_CLIENTE"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_CLIENTE" (
  "cli_sk" INT NOT NULL,
  "cli_cod" VARCHAR(5) NOT NULL,
  "cli_empresa" VARCHAR(45) NOT NULL,
  "cli_contato" VARCHAR(45) NULL,
  "cli_telefone" VARCHAR(45) NULL,
  "cli_cidade" VARCHAR(45) NOT NULL,
  "cli_país" VARCHAR(45) NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("cli_sk"));


-- -----------------------------------------------------
-- Table "public"."DIM_VENDEDOR"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_VENDEDOR" (
  "ven_sk" SERIAL NOT NULL,
  "ven_cod" INT NOT NULL,
  "ven_nomeCompleto" VARCHAR(45) NOT NULL,
  "ven_cargo" VARCHAR(45) NOT NULL,
  "ven_dataDeContrato" DATE NOT NULL,
  "ven_cidade" VARCHAR(45) NOT NULL,
  "ven_país" VARCHAR(45) NULL,
  "ven_supervisor" VARCHAR(45) NOT NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("ven_sk"));

-- -----------------------------------------------------
-- Table "public"."DIM_TRANSPORTADORA"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_TRANSPORTADORA" (
  "tran_sk" INT NOT NULL,
  "tran_cod" INT NOT NULL,
  "tran_nome" VARCHAR(45) NOT NULL,
  "tran_telefone" VARCHAR(45) NOT NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("tran_sk"));


-- -----------------------------------------------------
-- Table "public"."DIM_PRODUTO"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_PRODUTO" (
  "prod_sk" INT NOT NULL,
  "prod_cod" INT NOT NULL,
  "prod_nome" VARCHAR(45) NOT NULL,
  "prod_fornecedor" VARCHAR(45) NOT NULL,
  "prod_categoria" VARCHAR(45) NOT NULL,
  "prod_precoUnit" INT NOT NULL,
  "prod_precisaReposicao" BOOLEAN NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("prod_sk"));


-- -----------------------------------------------------
-- Table "public"."DIM_TEMPO_PEDIDO"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_TEMPO_PEDIDO" (
  "tpd_sk" INT NOT NULL,
  "tpd_data" DATE NULL,
  "tpd_ano" INTERVAL YEAR NULL,
  "tpd_mes" VARCHAR(45) NULL,
  "tpd_dia" VARCHAR(45) NULL,
  "tpd_diasemana" VARCHAR(45) NULL,
  "tpd_trimestre" VARCHAR(45) NULL,
  "tpd_semanaano" VARCHAR(45) NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("tpd_sk"));


-- -----------------------------------------------------
-- Table "public"."DIM_TEMPO_ENTREGA"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_TEMPO_ENTREGA" (
  "tet_sk" INT NOT NULL,
  "tet_data" DATE NULL,
  "tet_ano" INTERVAL YEAR NULL,
  "tet_mes" VARCHAR(45) NULL,
  "tet_dia" VARCHAR(45) NULL,
  "tet_diasemana" VARCHAR(45) NULL,
  "tet_trimestre" VARCHAR(45) NULL,
  "tet_semanaano" VARCHAR(45) NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("tet_sk"));


-- -----------------------------------------------------
-- Table "public"."DIM_TEMPO_EXPEDIÇÃO"
-- -----------------------------------------------------
CREATE TABLE  "public"."DIM_TEMPO_EXPEDIÇÃO" (
  "tep_sk" INT NOT NULL,
  "tep_data" DATE NULL,
  "tep_ano" INTERVAL YEAR NULL,
  "tep_mes" VARCHAR(45) NULL,
  "tep_dia" VARCHAR(45) NULL,
  "tep_diasemana" VARCHAR(45) NULL,
  "tep_trimestre" VARCHAR(45) NULL,
  "tep_semanaano" VARCHAR(45) NULL,
  "date_to" TIMESTAMP NOT NULL,
  "date_from" TIMESTAMP NOT NULL,
  "version" INT NOT NULL,
  PRIMARY KEY ("tep_sk"));


-- -----------------------------------------------------
-- Table "public"."FATO_PEDIDO"
-- -----------------------------------------------------
CREATE TABLE  "public"."FATO_PEDIDO" (
  "fat_cli_sk" INT NOT NULL,
  "fat_fun_sk" INT NOT NULL,
  "fat_tpd_sk" INT NOT NULL,
  "fat_tet_sk" INT NOT NULL,
  "fat_tep_sk" INT NOT NULL,
  "fat_tran_sk" INT NOT NULL,
  "fat_prod_sk" INT NOT NULL,
  "fat_numPedido" INT NOT NULL,
  "fat_freteItem" INT NOT NULL,
  "fat_paisDestino" VARCHAR(45) NOT NULL,
  "fat_precoUnit" INT NOT NULL,
  "fat_divergenciaPrecoVenda" BOOLEAN NULL,
  "fat_diasParaEntrega" INT NULL,
  "fat_diasParaExpedicao" INT NULL,
  "fat_descontoR$" INT NULL,
  "fat_desconto%" DOUBLE PRECISION NULL,
  "fat_valorVenda" INT NULL,
  CONSTRAINT "fk_Facto_Cliente"
    FOREIGN KEY ("fk_cli_cod")
    REFERENCES "public"."DIM_CLIENTE" ("cli_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Vendedor"
    FOREIGN KEY ("fk_fun_cod")
    REFERENCES "public"."DIM_VENDEDOR" ("ven_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Transportadora"
    FOREIGN KEY ("fk_tran_sk")
    REFERENCES "public"."DIM_TRANSPORTADORA" ("tran_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Produto"
    FOREIGN KEY ("fk_prod_sk")
    REFERENCES "public"."DIM_PRODUTO" ("prod_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Date_Pedido"
    FOREIGN KEY ("fk_date_pedido")
    REFERENCES "public"."DIM_TEMPO_PEDIDO" ("tpd_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Date_Entrega"
    FOREIGN KEY ("fk_date_entrega")
    REFERENCES "public"."DIM_TEMPO_ENTREGA" ("tet_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Date_Expedição"
    FOREIGN KEY ("fk_date_expedição")
    REFERENCES "public"."DIM_TEMPO_EXPEDIÇÃO" ("tep_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


