-- MySQL Script generated by MySQL Workbench
-- qui 05 dez 2019 22:00:50 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE "DM_Northwind"

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS "public"
CASCADE;

-- -----------------------------------------------------
-- Schema public
-- -----------------------------------------------------
CREATE SCHEMA
IF NOT EXISTS  "public"  ;

-- -----------------------------------------------------
-- Table "public"."DIM_CLIENTE"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_cliente"
(
  "cli_sk" BIGINT,
  "version" INTEGER,
  "date_from" TIMESTAMP,
  "date_to" TIMESTAMP,
  "cli_cod" VARCHAR(5),
  "cli_empresa" VARCHAR(40),
  "cli_contato" VARCHAR(30),
  "cli_telefone" VARCHAR(24),
  "cli_cidade" VARCHAR(15),
  "cli_pais" VARCHAR(15),
  PRIMARY KEY ("cli_sk")
);
CREATE INDEX idx_dim_cliente_lookup ON dim_cliente(cli_cod);
CREATE INDEX idx_dim_cliente_tk ON dim_cliente(cli_sk);
CREATE SEQUENCE cli_sk_seq START WITH 1 INCREMENT BY 1;


-- -----------------------------------------------------
-- Table "public"."DIM_VENDEDOR"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_vendedor"
(
  "ven_sk" BIGINT,
  "ven_cod" INTEGER,
  "ven_nome" TEXT,
  "ven_cargo" VARCHAR(30),
  "ven_datacontratacao" TIMESTAMP,
  "ven_cidade" VARCHAR(15),
  "ven_pais" VARCHAR(15),
  "ven_supervisor" INTEGER,
  "date_to" TIMESTAMP,
  "date_from" TIMESTAMP,
  "version" INTEGER,
  PRIMARY KEY ("ven_sk")
);
CREATE INDEX idx_dim_vendedor_lookup ON dim_vendedor(ven_cod);
CREATE INDEX idx_dim_vendedor_tk ON dim_vendedor(ven_sk);
CREATE SEQUENCE ven_sk_seq START WITH 1 INCREMENT BY 1;

-- -----------------------------------------------------
-- Table "public"."DIM_TRANSPORTADORA"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_transportadora"
(
  "tran_sk" BIGINT,
  "tran_cod" INTEGER,
  "tran_nome" VARCHAR(40),
  "tran_telefone" VARCHAR(24),
  "date_to" TIMESTAMP,
  "date_from" TIMESTAMP,
  "version" INTEGER,
  PRIMARY KEY ("tran_sk")
);
CREATE INDEX idx_dim_transportadora_lookup ON dim_transportadora(tran_cod);
CREATE INDEX idx_dim_transportadora_tk ON dim_transportadora(tran_sk);
CREATE SEQUENCE tran_sk_seq START WITH 1 INCREMENT BY 1;


-- -----------------------------------------------------
-- Table "public"."DIM_PRODUTO"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_produto"
(
  "prod_sk" BIGINT,
  "prod_cod" INTEGER,
  "prod_nome" VARCHAR(40),
  "prod_fornecedor" INTEGER,
  "prod_categoria" INTEGER,
  "prod_precounitario" DOUBLE PRECISION,
  "prod_precisareposicao" BOOLEAN,
  "date_to" TIMESTAMP,
  "date_from" TIMESTAMP,
  "version" INTEGER,
  PRIMARY KEY ("prod_sk")
);
CREATE INDEX idx_dim_produto_lookup ON dim_produto(prod_cod);
CREATE INDEX idx_dim_produto_tk ON dim_produto(prod_sk);
CREATE SEQUENCE prod_sk_seq START WITH 1 INCREMENT BY 1;


-- -----------------------------------------------------
-- Table "public"."DIM_TEMPO_PEDIDO"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_tempo_pedido"
(
  "tpd_sk" BIGINT,
  "tpd_data" TIMESTAMP,
  "tpd_ano" SMALLINT,
  "tpd_mes" SMALLINT,
  "tpd_dia" SMALLINT,
  "tpd_diasemana" SMALLINT,
  "tpd_trimestre" SMALLINT,
  "tpd_semanaano" SMALLINT,
  "date_to" TIMESTAMP,
  "date_from" TIMESTAMP,
  "version" INTEGER,
  PRIMARY KEY ("tpd_sk")
);
CREATE INDEX idx_dim_tempo_pedido_lookup ON dim_tempo_pedido(tpd_data);
CREATE INDEX idx_dim_tempo_pedido_tk ON dim_tempo_pedido(tpd_sk);
CREATE SEQUENCE tpd_sk_seq START WITH 1 INCREMENT BY 1;


-- -----------------------------------------------------
-- Table "public"."DIM_TEMPO_ENTREGA"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_tempo_entrega"
(
  "tet_sk" BIGINT,
  "tet_data" TIMESTAMP,
  "tet_ano" SMALLINT,
  "tet_mes" SMALLINT,
  "tet_dia" SMALLINT,
  "tet_diasemana" SMALLINT,
  "tet_trimestre" SMALLINT,
  "tet_semanaano" SMALLINT,
  "date_to" TIMESTAMP,
  "date_from" TIMESTAMP,
  "version" INTEGER,
  PRIMARY KEY ("tet_sk")
);
CREATE INDEX "idx_dim_tempo_entrega_lookup" ON dim_tempo_entrega("tet_data");
CREATE INDEX "idx_dim_tempo_entrega_tk" ON dim_tempo_entrega("tet_sk");
CREATE SEQUENCE "tet_sk_seq" START WITH 1 INCREMENT BY 1;

-- -----------------------------------------------------
-- Table "public"."DIM_TEMPO_EXPEDIÇÃO"
-- -----------------------------------------------------
CREATE TABLE "public"."dim_tempo_expedicao"
(
  "tep_sk" BIGINT,
  "tep_data" DATE NULL,
  "tep_ano" SMALLINT,
  "tep_mes" SMALLINT,
  "tep_dia" SMALLINT,
  "tep_diasemana" SMALLINT,
  "tep_trimestre" SMALLINT,
  "tep_semanaano" SMALLINT,
  "date_to" TIMESTAMP,
  "date_from" TIMESTAMP,
  "version" INTEGER,
  PRIMARY KEY ("tep_sk")
);
CREATE INDEX idx_dim_tempo_expedicao_lookup ON dim_tempo_expedicao(tep_data);
CREATE INDEX idx_dim_tempo_expedicao_tk ON dim_tempo_expedicao(tep_sk);
CREATE SEQUENCE tep_sk_seq START WITH 1 INCREMENT BY 1;


-- -----------------------------------------------------
-- Table "public"."FATO_PEDIDO"
-- -----------------------------------------------------
CREATE TABLE "public"."fato_vendas"
(
  "fat_cli_sk" INTEGER,
  "fat_fun_sk" INTEGER,
  "fat_tpd_sk" INTEGER,
  "fat_tet_sk" INTEGER,
  "fat_tep_sk" INTEGER,
  "fat_tran_sk" INTEGER,
  "fat_prod_sk" INTEGER,
  "fat_numpedido" INTEGER,
  "fat_freteitem" NUMERIC(16, 2),
  "fat_paisdestino" VARCHAR(15),
  "fat_precounit" INT NOT NULL,
  "fat_divergenciaprecovenda" DOUBLE PRECISION,
  "fat_diasparaentrega" INTEGER,
  "fat_diasparaexpedicao" INTEGER,
  "fat_descontor$" NUMERIC(16, 2),
  "fat_desconto%" DOUBLE PRECISION,
  "fat_valorvenda" DOUBLE PRECISION,
  CONSTRAINT "fk_Facto_Cliente"
    FOREIGN KEY ("fat_cli_sk")
    REFERENCES "public"."dim_cliente" ("cli_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Vendedor"
    FOREIGN KEY ("fat_fun_sk")
    REFERENCES "public"."dim_vendedor" ("ven_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Transportadora"
    FOREIGN KEY ("fat_tran_sk")
    REFERENCES "public"."dim_transportadora" ("tran_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Produto"
    FOREIGN KEY ("fat_prod_sk")
    REFERENCES "public"."dim_produto" ("prod_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Date_Pedido"
    FOREIGN KEY ("fat_tpd_sk")
    REFERENCES "public"."dim_tempo_pedido" ("tpd_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Date_Entrega"
    FOREIGN KEY ("fat_tet_sk")
    REFERENCES "public"."dim_tempo_entrega" ("tet_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_Facto_Date_Expedicao"
    FOREIGN KEY ("fat_tep_sk")
    REFERENCES "public"."dim_tempo_expedicao" ("tep_sk")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


